image:
  file: .gitpod.Dockerfile
tasks:
  - name: Storybook
    init: yarn bootstrap && yarn build
    command: yarn storybook
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
